[project]
name = "pythonproject1"
version = "0.0.1"
description = "Add your description here"
requires-python = "==3.12.*"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyterlab>=4.1.6",
    "nn>=0.1.1",
    "numpy>=2.3.5",
    "torch==2.7.1",
    "torchvision==0.22.1",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu118"
