[project]
name = "pythonproject1"
version = "0.0.1"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyterlab>=4.1.6",
    "numpy>=2.3.5",
    "torch>=2.10.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu126"

